import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const open_Sans = Open_Sans({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "INFLATABLE",
  description: "Generated by create next app",
  icons: {
    icon: ["/ic-logo.svg?v=4"],
    shortcut: ["/ic-logo.svg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_Sans.className}>{children}</body>
    </html>
  );
}
